# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '1 Step' do
  use_frameworks!

  pod 'Introspect'

  target '1 Step Tests' do
    inherit! :search_paths
  end

end
